export const IMAGE_CONSTANTS = {
    crown: require('../../assets/crown.png'),
    strawberryBg: require('../../assets/strawberry_bg.png'),
    successStoriesBg: require('../../assets/success-stories-bg.png'),
    check: require('../../assets/check.png'),
    star: require('../../assets/star.png'),
    checkPrimary: require('../../assets/check_primary.png'),
    checkMark: require('../../assets/check_mark.png'),
    macroCalculator: require('../../assets/macro-calculator.png'),
    macroDashboard: require('../../assets/macro-dashboard.png'),
    nearbyMealFinder: require('../../assets/nearby-meal-finder.png'),
    grilledSalmon: require('../../assets/grilled-salmon.png'),
    aiSuggestedMeals: require('../../assets/ai-suggested-meals.png'),
    backButton: require('../../assets/back-button.png'),
    notificationIcon: require('../../assets/notification-icon.png'),
    trophy: require('../../assets/trophy.png'),
    trophySvg: require('../../assets/trophy-svg.svg'),
    splashIcon: require('../../assets/splash-icon.png'),
    steakAndMashedPotatoes: require('../../assets/steak-and-mashed-potatoes.png'),
    sampleFood: require('../../assets/sample-food.png'),
    mealScan: require('../../assets/meal-scan.png'),
    caloriesIcon: require('../../assets/calories-icon.png'),
}