name: iOS Build and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      submit_to_testflight:
        description: 'Submit Macromeals to TestFlight'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  NODE_VERSION: 18.x

jobs:
  build-ios:
    name: Build iOS App
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.build.outputs.build-id }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build iOS app
        id: build
        run: |
          BUILD_OUTPUT=$(eas build --platform ios --profile production --non-interactive --json)
          BUILD_ID=$(echo $BUILD_OUTPUT | jq -r '.[0].id')
          echo "build-id=$BUILD_ID" >> $GITHUB_OUTPUT
          echo "Build started with ID: $BUILD_ID"

      - name: Wait for build to complete
        run: |
          eas build:wait --id ${{ steps.build.outputs.build-id }}

  submit-to-testflight:
    name: Submit to TestFlight
    needs: build-ios
    if: github.event.inputs.submit_to_testflight == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Submit to TestFlight
        run: |
          eas submit --platform ios --id ${{ needs.build-ios.outputs.build-id }} --non-interactive

  submit-to-app-store:
    name: Submit to App Store
    needs: build-ios
    if: github.event.inputs.submit_to_testflight == 'false' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: ubmit to App Store
        run: |
          eas submit --platform ios --id ${{ needs.build-ios.outputs.build-id }} --non-interactive --submit-to-app-store